name: Create GitHub Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get tag name
        id: get_tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - name: Extract changelog for this tag
        id: extract_changelog
        run: |
          TAG="${{ steps.get_tag.outputs.tag }}"
          # Escape dots for grep
          TAG_ESCAPED=$(echo "$TAG" | sed 's/\./\\./g')
          # Extract the section between the current tag and the next one
          awk "/^### \[$TAG_ESCAPED\]/ {printit=1; next} /^### \[.*\]/ {printit=0} printit" CHANGELOG.md > RELEASE_BODY.md

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          release_name: Release ${{ steps.get_tag.outputs.tag }}
          body_path: RELEASE_BODY.md
          draft: false
          prerelease: false
